_format_version: "2.1"
services:
  - name: rest
    url: http://rest:3000
    routes:
      - name: rest-route
        paths:
          - /
        strip_path: false
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth
  - name: storage
    url: http://storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage
  - name: realtime
    url: http://realtime:4000
    routes:
      - name: realtime-route
        paths:
          - /realtime
